# Generated by Django 4.2.5 on 2023-10-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.IntegerField()),
                ('metric_number', models.CharField(max_length=255)),
                ('product_color', models.CharField(choices=[('R', 'Red'), ('O', 'Orange'), ('Y', 'Yellow'), ('G', 'Green'), ('B', 'Blue'), ('V', 'Violet'), ('P', 'Pink'), ('W', 'White'), ('GY', 'Grey'), ('BK', 'Black'), ('NS', 'Not Specified')], default='NS', max_length=2)),
                ('product_section', models.CharField(choices=[('CG', 'Can Goods'), ('S', 'Sauces'), ('DB', 'Drinks and Beverages'), ('CS', 'Coffee and Sugar'), ('FF', 'Frozen Food'), ('MD', 'Milk and Dairy'), ('N', 'Noodles'), ('CN', 'Cup Noodles'), ('SS', 'Soup and Shampoo'), ('C', 'Chemicals'), ('M', 'Medicine'), ('CK', 'Crackers'), ('D', 'Diaper'), ('NS', 'Not Specified')], default='NS', max_length=2)),
                ('product_size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double XL'), ('XXXL', 'Triple XL'), ('NS', 'Not Specified')], default='NS', max_length=4)),
                ('metric_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_id', to='product.metric_unit')),
            ],
        ),
    ]
