# Generated by Django 4.2.5 on 2023-10-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150, unique=True)),
                ('network', models.CharField(choices=[('GLOBE', 'Globe'), ('SMART', 'Smart'), ('TNT', 'TNT'), ('SUN', 'Sun'), ('TM', 'TM'), ('DITO', 'Dito'), ('GOMO', 'Gomo'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=25)),
                ('load', models.CharField(max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='customer.customer')),
            ],
        ),
    ]
