# Generated by Django 4.2.5 on 2023-10-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('0', 'Others')], default='M', max_length=1)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact_no', models.CharField(max_length=15, unique=True)),
                ('civil_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widow')], default='S', max_length=1)),
                ('street', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
