# Generated by Django 4.2.7 on 2023-11-11 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0002_category_color_size_remove_product_product_section_and_more'),
        ('credit', '0002_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credited_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id_credit', to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='product.product')),
            ],
        ),
    ]
