# Generated by Django 4.2.7 on 2023-11-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_credit_transaction_item_product_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_transaction',
            name='payment_delay',
        ),
        migrations.AddField(
            model_name='credit_transaction',
            name='pending_days',
            field=models.IntegerField(null=True),
        ),
    ]
